GET http://localhost:3000/books HTTP/1.1

###
GET http://localhost:3000/books/1 HTTP/1.1

###
GET http://localhost:3000/books/2 HTTP/1.1

###
POST http://localhost:3000/books HTTP/1.1
Content-Type: application/json

{
    "titulo": "Harry Potter",
    "autor": "J.K",
    "año": 1998
}

###
PUT http://localhost:3000/books/3 HTTP/1.1
Content-Type: application/json

{
    "titulo": "Harry Potter y La Piedra Filosofal",
    "autor": "J.K",
    "año": 1999
}

###
DELETE  http://localhost:3000/books/3 HTTP/1.1